ifndef CONFIG_SITL
obj-y += configblockeeprom.o
else CONFIG_SITL
obj-y += configblocksitl.o
endif

obj-y += eprintf.o
obj-y += crc32.o
obj-y += debug.o
obj-y += cfassert.o
ifndef CONFIG_SITL
obj-y += clockCorrectionEngine.o
obj-y += cpuid.o
obj-y += buf2buf.o
endif

ifndef CONFIG_SITL
obj-y += FreeRTOS-openocd.o
endif
obj-y += filter.o

ifndef CONFIG_SITL
obj-y += sleepus.o
endif
obj-y += num.o
obj-y += rateSupervisor.o
obj-y += statsCnt.o

### Sub directories
ifndef CONFIG_SITL
obj-y += kve/
obj-y += tdoa/
obj-y += lighthouse/
endif


### Implementations for abort(), malloc() and free(), needed to interact with apps written in C++
ifndef CONFIG_SITL
obj-y += abort.o
obj-y += malloc.o
endif
obj-y += pid.o

### Rules for handling generated version.c
obj-y += version.o
version-objs := version_gen.o
src/utils/src/version_gen.c: src/utils/src/version.vtpl FORCE
	 $(PYTHON) $(srctree)/tools/make/versionTemplate.py --crazyflie-base $(srctree) $< $@
